import turtle
def rectangle(width, length, color, fill):
    turtle.up()
    turtle.setheading(0)
    turtle.pensize(1)
    turtle.pencolor(color)
    turtle.fillcolor(fill)
    turtle.begin_fill()
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(width)
    turtle.left(90)
    turtle.forward(length)
    turtle.left(90)
    turtle.forward(width)
    turtle.end_fill()

def triangle(x, y, base, color, fill):
    turtle.up()
    turtle.setheading(0)
    turtle.setx(x)
    turtle.sety(y)
    turtle.pensize(1)
    turtle.pencolor(color)
    turtle.fillcolor(fill)
    turtle.begin_fill()
    turtle.forward(base)
    turtle.left(120)
    turtle.forward(base)
    turtle.left(120)
    turtle.forward(base) 
    turtle.left(120)
    turtle.end_fill()

def circle(x, y, radius, pen_color, fill_color):
    turtle.up()
    turtle.setheading(0)
    turtle.setx(x)
    turtle.sety(y)
    turtle.pencolor(pen_color)
    turtle.begin_fill()
    turtle.fillcolor(fill_color)
    turtle.circle(radius)
    turtle.end_fill()

def main():
    rectangle(50, 70, 'red', 'red')
    turtle.down()
    triangle(-50, -50, 50, 'pink', 'pink')
    turtle.down()
    circle( -70, 70, 30, 'blue', 'blue')
    input('press key to continue')

main()